// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeGGN75NCAroKM7TmDdzBZZZG4TFJt-Rs',
    appId: '1:46359945356:web:71ad3d8acde80ad8eb9ba9',
    messagingSenderId: '46359945356',
    projectId: 'citygates-82da3',
    authDomain: 'citygates-82da3.firebaseapp.com',
    storageBucket: 'citygates-82da3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA20HvcVriGivnsNE7OpJqBFN7Zf6MdNB0',
    appId: '1:46359945356:android:ab299ec66609bd0ceb9ba9',
    messagingSenderId: '46359945356',
    projectId: 'citygates-82da3',
    storageBucket: 'citygates-82da3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwTmSQDliGlaN9r0160fE5L4Hw1XbMcU',
    appId: '1:46359945356:ios:e264a5e9acb3f0a3eb9ba9',
    messagingSenderId: '46359945356',
    projectId: 'citygates-82da3',
    storageBucket: 'citygates-82da3.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzwTmSQDliGlaN9r0160fE5L4Hw1XbMcU',
    appId: '1:46359945356:ios:e264a5e9acb3f0a3eb9ba9',
    messagingSenderId: '46359945356',
    projectId: 'citygates-82da3',
    storageBucket: 'citygates-82da3.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeGGN75NCAroKM7TmDdzBZZZG4TFJt-Rs',
    appId: '1:46359945356:web:f491834f0c5bd2a9eb9ba9',
    messagingSenderId: '46359945356',
    projectId: 'citygates-82da3',
    authDomain: 'citygates-82da3.firebaseapp.com',
    storageBucket: 'citygates-82da3.appspot.com',
  );
}
